#!/opt/local/bin/python
#  Date:   Aug 2014
#  Author: Britton J. Olson
#  Desc:   Convert sqlite database into an excel spreadsheet
#          (xls) file.
#  Notes:  Requires sqlite3 and xlwt python libraries
import sqlite3 as lite
import xlwt
import xlrd
import sys


db = sys.argv[1]
out = sys.argv[2]

con = lite.connect(db)
cur = con.cursor()

# Get column heads
cur.execute('pragma table_info(player)')
head = cur.fetchall()
# Get row entries
cur.execute('select * from player')
players = cur.fetchall()

# Open workbook and save head/body
workbook = xlwt.Workbook()
sheet = workbook.add_sheet('Sheet1')
# head
for col,item in enumerate(head):
    sheet.write(0,col,item[1])
# body
for row,player in enumerate(players):
    for col,item in enumerate(player):
        sheet.write(row+1,col,item)
# done
workbook.save(out)
