#!/usr/bin/python
#  Date:   Aug 2014
#  Author: Britton J. Olson
#  Desc:   Convert sqlite database into an excel spreadsheet
#          (xls) file.
#  Notes:  Requires sqlite3 and xlwt python libraries
import sqlite3 as lite
import xlwt
import xlrd
import sys
import math

db = sys.argv[1]
out = sys.argv[2]

con = lite.connect(db)
cur = con.cursor()


# Get all the tables in this database
cmd = "select name from sqlite_master where type = 'table' "
cur.execute(cmd)
tables = cur.fetchall()


import pdb;
workbook = xlwt.Workbook()
for table in tables:
    # Get column heads
    cur.execute('pragma table_info(%s)' % table[0] )
    head = cur.fetchall()
    # Get row entries
    cur.execute('select * from %s' % table[0] )
    players = cur.fetchall()


    Np = len(players)
    cmax = 30000     # Max character per cell
    Rmax = 64000     # Max number of rows per sheet
    NS = 1
    if ( Np > Rmax):
        NS = int(math.ceil( float(Np)/float(Rmax) ) )
    for ss in range(NS):
        ips = ss*(Rmax)
        ipe = min( (ss+1)*Rmax, Np)
        # Open workbook and save head/body
        print table[0]
        if (ss < 1 ):
            sheet = workbook.add_sheet(table[0])
        else:
            sheet = workbook.add_sheet(table[0] + '_%s' % (ss) )
        # head
        for col,item in enumerate(head):
            sheet.write(0,col,item[1])
        # body
        for row,player in enumerate(players[ips:ipe]):
            for col,item in enumerate(player):
                if ( type(item) == type(u'') ):
                    imax = min(cmax,len(item))
                    sheet.write(row+1,col,item[0:imax] )
                else:
                    sheet.write(row+1,col,item )
    # done

workbook.save(out)
